version: '3.9'

services:
  web:
    image: nginx:stable-alpine3.17
    restart: always
    environment:
      - VIRTUAL_HOST=live-channel.windowschannel.tv
      - LETSENCRYPT_HOST=live-channel.windowschannel.tv
      - LETSENCRYPT_EMAIL=info@windowschannel.com
    expose:
      - "80"
    volumes:
      - ./html:/usr/share/nginx/html

networks:
  default:
    name: streaming
    external: true
